// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-jj1scnSIcsWhxztDQrLhS2mbgtBriyg',
    appId: '1:940297251688:web:a24e3a0c839d9baf5684dd',
    messagingSenderId: '940297251688',
    projectId: 'eco-scan-fd525',
    authDomain: 'eco-scan-fd525.firebaseapp.com',
    storageBucket: 'eco-scan-fd525.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7BMzua12XE6gqiyIfkTN4XpYHDH_3dng',
    appId: '1:940297251688:android:267636e6795531c75684dd',
    messagingSenderId: '940297251688',
    projectId: 'eco-scan-fd525',
    storageBucket: 'eco-scan-fd525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5cgagHG39wFJy2Zavb0N2_Ah-2sl8ceI',
    appId: '1:940297251688:ios:e15ba71d26c3a53f5684dd',
    messagingSenderId: '940297251688',
    projectId: 'eco-scan-fd525',
    storageBucket: 'eco-scan-fd525.appspot.com',
    iosBundleId: 'com.example.barcodeScanner',
  );
}
